name: Lint

on:
  pull_request:
    branches:
      - "**"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: "--ext .jsx,.js,.ts,.tsx ."
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-review
          stylelint_input: "src/**/*.css"
