name: Lint

on:
  pull_request:
    branches:
      - "**"

jobs:
  eslint:
    name: eslint (reviewdog)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - uses: reviewdog/action-eslint@v1.14.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_on_error: true
          eslint_flags: "--ext .js,.ts,.tsx ."
  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run stylelint
